Global Youtube Statistics

In [19]:
import pandas as pd
import numpy as np
import re

In [20]:
# LOADING RAW DATASET (RAW BACKUP)
# This 'df' will remain untouched as raw backup
df = pd.read_csv(
    r"F:\Data Analytics Real time Project portfolio\Global Youtube Statistics\Global YouTube Statistics.csv", 
    encoding='latin-1'
)

In [21]:
# Disable scientific notation globally so numbers look clean
pd.set_option('display.float_format', lambda x: '%.0f' % x)

In [22]:
# CREATING A WORKSET COPY (DUPLICATE DATASET)
# We make a duplicate copy of 'df' and name it 'df_cleaned'. All cleaning happens here.
df_cleaned = df.copy()

In [23]:
# 1. Clear any truncation limits for rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# 2. Display the dataframe again
df_cleaned

     rank                                           Youtuber  subscribers  \
0       1                                           T-Series    245000000
1       2                                     YouTube Movies    170000000
2       3                                            MrBeast    166000000
3       4                         Cocomelon - Nursery Rhymes    162000000
4       5                                          SET India    159000000
5       6                                              Music    119000000
6       7                                ýýý Kids Diana Show    112000000
7       8                                          PewDiePie    111000000
8       9                                        Like Nastya    106000000
9      10                                      Vlad and Niki     98900000
10     11                                  Zee Music Company     96700000
11     12                                                WWE     96000000
12     13                                             Gaming     93600000
13     14                                          BLACKPINK     89800000
14     15                                          Goldmines     86900000
15     16                                           Sony SAB     83000000
16     17                                    5-Minute Crafts     80100000
17     18                                          BANGTANTV     75600000
18     19                                             Sports     75000000
19     20                                      Justin Bieber     71600000
20     21                                        HYBE LABELS     71300000
21     22                                             Zee TV     70500000
22     23        Pinkfong Baby Shark - Kids' Songs & Stories     68200000
23     24                                    Canal KondZilla     66500000
24     25              ChuChu TV Nursery Rhymes & Kids Songs     65900000
25     26                               Shemaroo Filmi Gaane     65600000
26     27                                          Colors TV     64600000
27     28                              T-Series Bhakti Sagar     61000000
28     29                                       Dude Perfect     59500000
29     30                                         Movieclips     59500000
30     31                                      Tips Official     59300000
31     32                                  El Reino Infantil     58400000
32     33                                         Wave Music     58000000
33     34                                            Aaj Tak     57600000
34     35                                   Sony Music India     57200000
35     36                                        EminemMusic     56900000
36     37                                         Marshmello     56400000
37     38                                                YRF     54600000
38     39  LooLoo Kids - Nursery Rhymes and Children's Songs     54000000
39     40                                         Ed Sheeran     53500000
40     41                                  Infobells - Hindi     53300000
41     42                                       Taylor Swift     52900000
42     43                                      Ariana Grande     52700000
43     44   BillionSurpriseToys  - Nursery Rhymes & Cartoons     52200000
44     45                                        JuegaGerman     48100000
45     46                                      Billie Eilish     47900000
46     47                                         Get Movies     47500000
47     48                                           Shemaroo     47400000
48     49                                            Badabun     46800000
49     50                                 SonyMusicIndiaVEVO     46600000
50     51                                                 A4     46300000
51     52                                          Bad Bunny     46100000
52     53                                         Fernanfloo     46100000
53     54                                          Voot Kids     45500000
54     55                                        Felipe Neto     45200000
55     56                                       Vocï¿½ï¿½ï¿½     44700000
56     57                                        HAR PAL GEO     44600000
57     58                                        BRIGHT SIDE     44500000
58     59                                         Katy Perry     44200000
59     60                                   whinderssonnunes     44200000
60     61                              ABS-CBN Entertainment     44200000
61     62                                        Alan Walker     43700000
62     63                                     HolaSoyGerman.     43600000
63     64                                            Shakira     43500000
64     65                         ýýýýýýýý ýý ýýýýýýýýýýýýýý     43200000
65     66                                     ARY Digital HD     43200000
66     67                                      Speed Records     42500000
67     68                                 Masha and The Bear     42400000
68     69                                   Like Nastya Show     42400000
69     70                                            Rihanna     41900000
70     71                                       Ishtar Music     41400000
71     72                                    Kimberly Loaiza     41300000
72     73      Little Baby Bum - Nursery Rhymes & Kids Songs     40900000
73     74                                   Luisito Comunica     40600000
74     75                                        elrubiusOMG     40400000
75     76                                    Toys and Colors     40300000
76     77                                     shfa2 - ï¿½ï¿½     39700000
77     78                          LUCCAS NETO - LUCCAS TOON     39400000
78     79                                        CarryMinati     39200000
79     80                                       XXXTENTACION     39200000
80     81                    Super Simple Songs - Kids Songs     39200000
81     82                                          Mikecrack     39100000
82     83                                  WorkpointOfficial     39000000
83     84                                        GR6 EXPLODE     38900000
84     85                                         TEDx Talks     38600000
85     86                                               shfa     38400000
86     87                        Goldmines Gaane Sune Ansune     38300000
87     88                                      One Direction     38200000
88     89                                       TheEllenShow     38200000
89     90                                           Sony PAL     38200000
90     91                                       Daddy Yankee     38000000
91     92                                      Vlad vï¿½ï¿½ï     37900000
92     93                                    Like Nastya ESP     37600000
93     94                                 ýýýýýýýýýýýý one31     37500000
94     95                                  Jkk Entertainment     37200000
95     96                                           ABP NEWS     37000000
96     97                                   Maria Clara & JP     37000000
97     98                                         Bruno Mars     36700000
98     99                                           Maroon 5     36600000
99    100                                    Ultra Bollywood     36600000
100   101                                       PowerKids TV     36500000
101   102                                            YouTube     36300000
102   103                                               News     36300000
103   104                                              Ozuna     36200000
104   105                                     MrBeast Gaming     36100000
105   106                                La Granja de Zenï¿½     35700000
106   107                                     Saregama Music     35500000
107   108                                            IndiaTV     35500000
108   109                        T-Series Bollywood Classics     35400000
109   110                                       Total Gaming     35400000
110   111                                         Markiplier     35200000
111   112                                       Ryan's World     35200000
112   113   Genevieve's Playhouse - Learning Videos for Kids     34900000
113   114                               T-Series Apna Punjab     34600000
114   115                                      Techno Gamerz     34400000
115   116                                           Geet MP3     34300000
116   117                                           J Balvin     34100000
117   118                                      Jess No Limit     34000000
118   119                                       Jingle Toons     34000000
119   120                                         VEGETTA777     33800000
120   121                                 Galinha Pintadinha     33800000
121   122                                       SSSniperWolf     33700000
122   123                                 Desi Music Factory     33700000
123   124                                       Selena Gomez     33600000
124   125                                            Rajshri     33500000
125   126                                        Ch3Thailand     33500000
126   127                                   KHANDESHI MOVIES     33500000
127   128                                  NoCopyrightSounds     33400000
128   129                         CVS 3D Rhymes & Kids Songs     33400000
129   130                                     Ricis Official     33300000
130   131                  BabyBus - Kids Songs and Cartoons     32800000
131   132                                     Eros Now Music     32700000
132   133                                      BETER Bï¿½ï¿½     32700000
133   134                                    DisneyMusicVEVO     32700000
134   135                                         The Weeknd     32600000
135   136                                            WowKidz     32200000
136   137                                            KAROL G     32100000
137   138                                            Mr Bean     32100000
138   139                                        rezendeevil     32100000
139   140                                           StarPlus     32000000
140   141                                             SMTOWN     31900000
141   142                                       GMA  Network     31900000
142   143                                             GENIAL     31800000
143   144                                  MR. INDIAN HACKER     31700000
144   145                         Worldwide Records Bhojpuri     31700000
145   146                                        DONA ï¿½ï¿½     31700000
146   147                                              Dream     31700000
147   148                                   Lucas and Marcus     31600000
148   149                                   JustinBieberVEVO     31600000
149   150                                         Luis Fonsi     31400000
150   151                       Peppa Pig - Official Channel     31400000
151   152                                     YOLO AVENTURAS     31200000
152   153             The Tonight Show Starring Jimmy Fallon     31200000
153   154                                          TheDonato     31200000
154   155                                     ImagineDragons     30700000
155   156                                 Diana and Roma ESP     30700000
156   157                                         Round2hell     30700000
157   158                                           Zee News     30500000
158   159                                            AboFlah     30500000
159   160                                                 AH     30400000
160   161                                        Trap Nation     30400000
161   162          ýýýýýýýýýýýýýýý ýýýýýý ýýýýýýýýýýýýýýýýýý     30400000
162   163        Boram Tube Vlog [ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿     30300000
163   164                                              Adele     30200000
164   165                                        Talking Tom     30200000
165   166      ýýýýýýýý ýýýýýýýý ýýýýýýýýýý | toyoraljanahtv     30200000
166   167                                      Frost Diamond     30100000
167   168                                   Spinnin' Records     30100000
168   169          Little Angel: Nursery Rhymes & Kids Songs     30100000
169   170                                      jacksepticeye     30100000
170   171                                       Shawn Mendes     30000000
171   172                            ashish chanchlani vines     29800000
172   173                                      Ultra Records     29600000
173   174                                 Popular on YouTube     29300000
174   175                                             Maluma     29300000
175   176                                              Zhong     29200000
176   177                                          Enaldinho     29200000
177   178                                          AuronPlay     29200000
178   179                                       Shorts Break     29000000
179   180                                  infobells - Tamil     28900000
180   181                                 Aditya Music India     28500000
181   182               The Late Late Show with James Corden     28400000
182   183                                      Aditya Movies     28400000
183   184                                     Masha y el Oso     28300000
184   185                                 infobells - Telugu     28300000
185   186                                             HUM TV     28300000
186   187                                    Shemaroo Movies     28200000
187   188                                    Michael Jackson     28200000
188   189                                              Drake     28100000
189   190                                  Goldmines Dishoom     28000000
190   191                                 Sandeep Maheshwari     27800000
191   192                         Bounce Patrol - Kids Songs     27800000
192   193                                        toycantando     27700000
193   194                                          MrBeast 2     27500000
194   195                                        Wiz Khalifa     27500000
195   196                                  JYP Entertainment     27400000
196   197                                 ýýý Kids Roma Show     27400000
197   198                                             DanTDM     27400000
198   199                                           Nick Jr.     27300000
199   200                                          Crazy XYZ     27300000
200   201                                       ToyPuddingTV     27100000
201   202                                   Dushyant kukreja     27100000
202   203                                      Gulshan Kalra     27100000
203   204                                       Brent Rivera     27000000
204   205                                   Renato Garcia YT     26900000
205   206                                       Beast Reacts     26700000
206   207                                          enchufetv     26700000
207   208                                            Netflix     26700000
208   209                              Raffy Tulfo in Action     26500000
209   210                                    WORLDSTARHIPHOP     26500000
210   211                                Goldmines Bollywood     26400000
211   212                                   Alan Chikin Chow     26400000
212   213                                          PANDA BOI     26400000
213   214                                        BB Ki Vines     26300000
214   215                                         D Billions     26200000
215   216                                 Junya.ï¿½ï¿½ï¿½ï¿½     26200000
216   217                                              Smosh     26100000
217   218                              1MILLION Dance Studio     26100000
218   219                                           NichLmao     26000000
219   220                                           Beyoncï¿     26000000
220   221                                 Marï¿½ï¿½ï¿½ï¿½ï¿½     26000000
221   222                                           Indosiar     25900000
222   223                                       VanossGaming     25800000
223   224                                       David Guetta     25700000
224   225                                      LosPolinesios     25700000
225   226                                        Nicki Minaj     25700000
226   227                                      Fede Vigevani     25600000
227   228                                    TaylorSwiftVEVO     25600000
228   229                                                ZHC     25500000
229   230                                        Post Malone     25500000
230   231                                 Rans Entertainment     25400000
231   232                                           LankyBox     25400000
232   233                                           Coldplay     25300000
233   234                                        Las Ratitas     25200000
234   235                                            WB Kids     25200000
235   236                                            ABPLIVE     25200000
236   237                                        Chris Brown     25200000
237   238                                      The Lallantop     25200000
238   239                                        RihannaVEVO     25100000
239   240                                      WatchMojo.com     25100000
240   241                                    TRANS7 OFFICIAL     25000000
241   242                                           Anuel AA     25000000
242   243                                         Dan Rhodes     24800000
243   244                                               Yuya     24800000
244   245                               America's Got Talent     24800000
245   246                                        mujjuu___14     24800000
246   247                                         EminemVEVO     24700000
247   248                                         Chloe Ting     24700000
248   249                                      KatyPerryVEVO     24600000
249   250                                         Mark Rober     24600000
250   251                               1theK (ï¿½ï¿½ï¿½ï¿½ï     24500000
251   252                                     Like Nastya AE     24400000
252   253                                       Amit Bhadana     24300000
253   254                                         Pen Movies     24300000
254   255                                MrBeast en Espaï¿½ï     24200000
255   256                                    shfa show India     24200000
256   257           Super JoJo - Nursery Rhymes & Kids Songs     24100000
257   258                                         Alejo Igoa     24100000
258   259                                     Daniel LaBelle     24100000
259   260                                        netd mï¿½ï¿     24100000
260   261                                           DJ Snake     24100000
261   262                                 Diana and Roma ARA     24100000
262   263                                                KSI     24100000
263   264                                       Spider Slack     24000000
264   265                                   Goldmines Movies     24000000
265   266                                            Preston     24000000
266   267                                      James Charles     23900000
267   268                                        Collins Key     23900000
268   269                                  Diana and Roma EN     23900000

In [24]:
# CLEANING TEXT COLUMNS (REMOVING EMOJIS & NON-ENGLISH CHARACTERS)

# Defining a function that keeps only English alphabets, numbers, and basic punctuation
def clean_text(text):
    if pd.isna(text):
        return text  # If the cell is empty (NaN), leave it as it is
    
    text = str(text)
    # REGEX: Keeps only English letters, numbers, spaces, and standard dashes
    cleaned = re.sub(r'[^a-zA-Z0-9\s\-_.,()]', '', text)
    cleaned = " ".join(cleaned.split())
    return cleaned

# List of text columns we want to convert in English text
text_columns = ['Youtuber', 'category', 'Title', 'Country', 'channel_type']

In [25]:
# Applying the cleaning function ONLY to our duplicate dataframe 'df_cleaned'
for col in text_columns:
    if col in df_cleaned.columns:
        df_cleaned[col] = df_cleaned[col].apply(clean_text)

# 1. Clear any truncation limits for rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# 2. Display the dataframe again
df_cleaned

     rank                                          Youtuber  subscribers  \
0       1                                          T-Series    245000000
1       2                                    YouTube Movies    170000000
2       3                                           MrBeast    166000000
3       4                        Cocomelon - Nursery Rhymes    162000000
4       5                                         SET India    159000000
5       6                                             Music    119000000
6       7                                   Kids Diana Show    112000000
7       8                                         PewDiePie    111000000
8       9                                       Like Nastya    106000000
9      10                                     Vlad and Niki     98900000
10     11                                 Zee Music Company     96700000
11     12                                               WWE     96000000
12     13                                            Gaming     93600000
13     14                                         BLACKPINK     89800000
14     15                                         Goldmines     86900000
15     16                                          Sony SAB     83000000
16     17                                   5-Minute Crafts     80100000
17     18                                         BANGTANTV     75600000
18     19                                            Sports     75000000
19     20                                     Justin Bieber     71600000
20     21                                       HYBE LABELS     71300000
21     22                                            Zee TV     70500000
22     23          Pinkfong Baby Shark - Kids Songs Stories     68200000
23     24                                   Canal KondZilla     66500000
24     25               ChuChu TV Nursery Rhymes Kids Songs     65900000
25     26                              Shemaroo Filmi Gaane     65600000
26     27                                         Colors TV     64600000
27     28                             T-Series Bhakti Sagar     61000000
28     29                                      Dude Perfect     59500000
29     30                                        Movieclips     59500000
30     31                                     Tips Official     59300000
31     32                                 El Reino Infantil     58400000
32     33                                        Wave Music     58000000
33     34                                           Aaj Tak     57600000
34     35                                  Sony Music India     57200000
35     36                                       EminemMusic     56900000
36     37                                        Marshmello     56400000
37     38                                               YRF     54600000
38     39  LooLoo Kids - Nursery Rhymes and Childrens Songs     54000000
39     40                                        Ed Sheeran     53500000
40     41                                 Infobells - Hindi     53300000
41     42                                      Taylor Swift     52900000
42     43                                     Ariana Grande     52700000
43     44     BillionSurpriseToys - Nursery Rhymes Cartoons     52200000
44     45                                       JuegaGerman     48100000
45     46                                     Billie Eilish     47900000
46     47                                        Get Movies     47500000
47     48                                          Shemaroo     47400000
48     49                                           Badabun     46800000
49     50                                SonyMusicIndiaVEVO     46600000
50     51                                                A4     46300000
51     52                                         Bad Bunny     46100000
52     53                                        Fernanfloo     46100000
53     54                                         Voot Kids     45500000
54     55                                       Felipe Neto     45200000
55     56                                               Voc     44700000
56     57                                       HAR PAL GEO     44600000
57     58                                       BRIGHT SIDE     44500000
58     59                                        Katy Perry     44200000
59     60                                  whinderssonnunes     44200000
60     61                             ABS-CBN Entertainment     44200000
61     62                                       Alan Walker     43700000
62     63                                    HolaSoyGerman.     43600000
63     64                                           Shakira     43500000
64     65                                                       43200000
65     66                                    ARY Digital HD     43200000
66     67                                     Speed Records     42500000
67     68                                Masha and The Bear     42400000
68     69                                  Like Nastya Show     42400000
69     70                                           Rihanna     41900000
70     71                                      Ishtar Music     41400000
71     72                                   Kimberly Loaiza     41300000
72     73       Little Baby Bum - Nursery Rhymes Kids Songs     40900000
73     74                                  Luisito Comunica     40600000
74     75                                       elrubiusOMG     40400000
75     76                                   Toys and Colors     40300000
76     77                                           shfa2 -     39700000
77     78                         LUCCAS NETO - LUCCAS TOON     39400000
78     79                                       CarryMinati     39200000
79     80                                      XXXTENTACION     39200000
80     81                   Super Simple Songs - Kids Songs     39200000
81     82                                         Mikecrack     39100000
82     83                                 WorkpointOfficial     39000000
83     84                                       GR6 EXPLODE     38900000
84     85                                        TEDx Talks     38600000
85     86                                              shfa     38400000
86     87                       Goldmines Gaane Sune Ansune     38300000
87     88                                     One Direction     38200000
88     89                                      TheEllenShow     38200000
89     90                                          Sony PAL     38200000
90     91                                      Daddy Yankee     38000000
91     92                                            Vlad v     37900000
92     93                                   Like Nastya ESP     37600000
93     94                                             one31     37500000
94     95                                 Jkk Entertainment     37200000
95     96                                          ABP NEWS     37000000
96     97                                    Maria Clara JP     37000000
97     98                                        Bruno Mars     36700000
98     99                                          Maroon 5     36600000
99    100                                   Ultra Bollywood     36600000
100   101                                      PowerKids TV     36500000
101   102                                           YouTube     36300000
102   103                                              News     36300000
103   104                                             Ozuna     36200000
104   105                                    MrBeast Gaming     36100000
105   106                                  La Granja de Zen     35700000
106   107                                    Saregama Music     35500000
107   108                                           IndiaTV     35500000
108   109                       T-Series Bollywood Classics     35400000
109   110                                      Total Gaming     35400000
110   111                                        Markiplier     35200000
111   112                                       Ryans World     35200000
112   113   Genevieves Playhouse - Learning Videos for Kids     34900000
113   114                              T-Series Apna Punjab     34600000
114   115                                     Techno Gamerz     34400000
115   116                                          Geet MP3     34300000
116   117                                          J Balvin     34100000
117   118                                     Jess No Limit     34000000
118   119                                      Jingle Toons     34000000
119   120                                        VEGETTA777     33800000
120   121                                Galinha Pintadinha     33800000
121   122                                      SSSniperWolf     33700000
122   123                                Desi Music Factory     33700000
123   124                                      Selena Gomez     33600000
124   125                                           Rajshri     33500000
125   126                                       Ch3Thailand     33500000
126   127                                  KHANDESHI MOVIES     33500000
127   128                                 NoCopyrightSounds     33400000
128   129                          CVS 3D Rhymes Kids Songs     33400000
129   130                                    Ricis Official     33300000
130   131                 BabyBus - Kids Songs and Cartoons     32800000
131   132                                    Eros Now Music     32700000
132   133                                           BETER B     32700000
133   134                                   DisneyMusicVEVO     32700000
134   135                                        The Weeknd     32600000
135   136                                           WowKidz     32200000
136   137                                           KAROL G     32100000
137   138                                           Mr Bean     32100000
138   139                                       rezendeevil     32100000
139   140                                          StarPlus     32000000
140   141                                            SMTOWN     31900000
141   142                                       GMA Network     31900000
142   143                                            GENIAL     31800000
143   144                                 MR. INDIAN HACKER     31700000
144   145                        Worldwide Records Bhojpuri     31700000
145   146                                              DONA     31700000
146   147                                             Dream     31700000
147   148                                  Lucas and Marcus     31600000
148   149                                  JustinBieberVEVO     31600000
149   150                                        Luis Fonsi     31400000
150   151                      Peppa Pig - Official Channel     31400000
151   152                                    YOLO AVENTURAS     31200000
152   153            The Tonight Show Starring Jimmy Fallon     31200000
153   154                                         TheDonato     31200000
154   155                                    ImagineDragons     30700000
155   156                                Diana and Roma ESP     30700000
156   157                                        Round2hell     30700000
157   158                                          Zee News     30500000
158   159                                           AboFlah     30500000
159   160                                                AH     30400000
160   161                                       Trap Nation     30400000
161   162                                                       30400000
162   163                                   Boram Tube Vlog     30300000
163   164                                             Adele     30200000
164   165                                       Talking Tom     30200000
165   166                                    toyoraljanahtv     30200000
166   167                                     Frost Diamond     30100000
167   168                                   Spinnin Records     30100000
168   169            Little Angel Nursery Rhymes Kids Songs     30100000
169   170                                     jacksepticeye     30100000
170   171                                      Shawn Mendes     30000000
171   172                           ashish chanchlani vines     29800000
172   173                                     Ultra Records     29600000
173   174                                Popular on YouTube     29300000
174   175                                            Maluma     29300000
175   176                                             Zhong     29200000
176   177                                         Enaldinho     29200000
177   178                                         AuronPlay     29200000
178   179                                      Shorts Break     29000000
179   180                                 infobells - Tamil     28900000
180   181                                Aditya Music India     28500000
181   182              The Late Late Show with James Corden     28400000
182   183                                     Aditya Movies     28400000
183   184                                    Masha y el Oso     28300000
184   185                                infobells - Telugu     28300000
185   186                                            HUM TV     28300000
186   187                                   Shemaroo Movies     28200000
187   188                                   Michael Jackson     28200000
188   189                                             Drake     28100000
189   190                                 Goldmines Dishoom     28000000
190   191                                Sandeep Maheshwari     27800000
191   192                        Bounce Patrol - Kids Songs     27800000
192   193                                       toycantando     27700000
193   194                                         MrBeast 2     27500000
194   195                                       Wiz Khalifa     27500000
195   196                                 JYP Entertainment     27400000
196   197                                    Kids Roma Show     27400000
197   198                                            DanTDM     27400000
198   199                                          Nick Jr.     27300000
199   200                                         Crazy XYZ     27300000
200   201                                      ToyPuddingTV     27100000
201   202                                  Dushyant kukreja     27100000
202   203                                     Gulshan Kalra     27100000
203   204                                      Brent Rivera     27000000
204   205                                  Renato Garcia YT     26900000
205   206                                      Beast Reacts     26700000
206   207                                         enchufetv     26700000
207   208                                           Netflix     26700000
208   209                             Raffy Tulfo in Action     26500000
209   210                                   WORLDSTARHIPHOP     26500000
210   211                               Goldmines Bollywood     26400000
211   212                                  Alan Chikin Chow     26400000
212   213                                         PANDA BOI     26400000
213   214                                       BB Ki Vines     26300000
214   215                                        D Billions     26200000
215   216                                            Junya.     26200000
216   217                                             Smosh     26100000
217   218                             1MILLION Dance Studio     26100000
218   219                                          NichLmao     26000000
219   220                                            Beyonc     26000000
220   221                                               Mar     26000000
221   222                                          Indosiar     25900000
222   223                                      VanossGaming     25800000
223   224                                      David Guetta     25700000
224   225                                     LosPolinesios     25700000
225   226                                       Nicki Minaj     25700000
226   227                                     Fede Vigevani     25600000
227   228                                   TaylorSwiftVEVO     25600000
228   229                                               ZHC     25500000
229   230                                       Post Malone     25500000
230   231                                Rans Entertainment     25400000
231   232                                          LankyBox     25400000
232   233                                          Coldplay     25300000
233   234                                       Las Ratitas     25200000
234   235                                           WB Kids     25200000
235   236                                           ABPLIVE     25200000
236   237                                       Chris Brown     25200000
237   238                                     The Lallantop     25200000
238   239                                       RihannaVEVO     25100000
239   240                                     WatchMojo.com     25100000
240   241                                   TRANS7 OFFICIAL     25000000
241   242                                          Anuel AA     25000000
242   243                                        Dan Rhodes     24800000
243   244                                              Yuya     24800000
244   245                               Americas Got Talent     24800000
245   246                                       mujjuu___14     24800000
246   247                                        EminemVEVO     24700000
247   248                                        Chloe Ting     24700000
248   249                                     KatyPerryVEVO     24600000
249   250                                        Mark Rober     24600000
250   251                                           1theK (     24500000
251   252                                    Like Nastya AE     24400000
252   253                                      Amit Bhadana     24300000
253   254                                        Pen Movies     24300000
254   255                                   MrBeast en Espa     24200000
255   256                                   shfa show India     24200000
256   257            Super JoJo - Nursery Rhymes Kids Songs     24100000
257   258                                        Alejo Igoa     24100000
258   259                                    Daniel LaBelle     24100000
259   260                                            netd m     24100000
260   261                                          DJ Snake     24100000
261   262                                Diana and Roma ARA     24100000
262   263                                               KSI     24100000
263   264                                      Spider Slack     24000000
264   265                                  Goldmines Movies     24000000
265   266                                           Preston     24000000
266   267                                     James Charles     23900000
267   268                                       Collins Key     23900000
268   269                                 Diana and Roma EN     23900000
269   270                               Venus Entertainment     23800000
270   271                                       Troom Troom     23800000
271   272                                  Enrique Iglesias     23800000

In [26]:
# Data Cleaning Process

# Step 1. Remove dupliates
# Step 2. Data Standarization
# STep 3. Remove Null values and blank values 
# Step 4. Remove unnecessary columns 

# So we have alot of null values and blank values so we will start from step 3

# STep 3. Remove Null values and blank values 

# 3.1. Replace empty blanks/spaces ('') with 0
df_cleaned = df_cleaned.replace(r'^\s*$', 0, regex=True)

# 3.2. Replace all NaN (Null) values with "Unknown"
df_cleaned = df_cleaned.fillna("Unknown")

# 1. Clear any truncation limits for rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# 2. Display the dataframe again
df_cleaned

     rank                                          Youtuber  subscribers  \
0       1                                          T-Series    245000000
1       2                                    YouTube Movies    170000000
2       3                                           MrBeast    166000000
3       4                        Cocomelon - Nursery Rhymes    162000000
4       5                                         SET India    159000000
5       6                                             Music    119000000
6       7                                   Kids Diana Show    112000000
7       8                                         PewDiePie    111000000
8       9                                       Like Nastya    106000000
9      10                                     Vlad and Niki     98900000
10     11                                 Zee Music Company     96700000
11     12                                               WWE     96000000
12     13                                            Gaming     93600000
13     14                                         BLACKPINK     89800000
14     15                                         Goldmines     86900000
15     16                                          Sony SAB     83000000
16     17                                   5-Minute Crafts     80100000
17     18                                         BANGTANTV     75600000
18     19                                            Sports     75000000
19     20                                     Justin Bieber     71600000
20     21                                       HYBE LABELS     71300000
21     22                                            Zee TV     70500000
22     23          Pinkfong Baby Shark - Kids Songs Stories     68200000
23     24                                   Canal KondZilla     66500000
24     25               ChuChu TV Nursery Rhymes Kids Songs     65900000
25     26                              Shemaroo Filmi Gaane     65600000
26     27                                         Colors TV     64600000
27     28                             T-Series Bhakti Sagar     61000000
28     29                                      Dude Perfect     59500000
29     30                                        Movieclips     59500000
30     31                                     Tips Official     59300000
31     32                                 El Reino Infantil     58400000
32     33                                        Wave Music     58000000
33     34                                           Aaj Tak     57600000
34     35                                  Sony Music India     57200000
35     36                                       EminemMusic     56900000
36     37                                        Marshmello     56400000
37     38                                               YRF     54600000
38     39  LooLoo Kids - Nursery Rhymes and Childrens Songs     54000000
39     40                                        Ed Sheeran     53500000
40     41                                 Infobells - Hindi     53300000
41     42                                      Taylor Swift     52900000
42     43                                     Ariana Grande     52700000
43     44     BillionSurpriseToys - Nursery Rhymes Cartoons     52200000
44     45                                       JuegaGerman     48100000
45     46                                     Billie Eilish     47900000
46     47                                        Get Movies     47500000
47     48                                          Shemaroo     47400000
48     49                                           Badabun     46800000
49     50                                SonyMusicIndiaVEVO     46600000
50     51                                                A4     46300000
51     52                                         Bad Bunny     46100000
52     53                                        Fernanfloo     46100000
53     54                                         Voot Kids     45500000
54     55                                       Felipe Neto     45200000
55     56                                               Voc     44700000
56     57                                       HAR PAL GEO     44600000
57     58                                       BRIGHT SIDE     44500000
58     59                                        Katy Perry     44200000
59     60                                  whinderssonnunes     44200000
60     61                             ABS-CBN Entertainment     44200000
61     62                                       Alan Walker     43700000
62     63                                    HolaSoyGerman.     43600000
63     64                                           Shakira     43500000
64     65                                                 0     43200000
65     66                                    ARY Digital HD     43200000
66     67                                     Speed Records     42500000
67     68                                Masha and The Bear     42400000
68     69                                  Like Nastya Show     42400000
69     70                                           Rihanna     41900000
70     71                                      Ishtar Music     41400000
71     72                                   Kimberly Loaiza     41300000
72     73       Little Baby Bum - Nursery Rhymes Kids Songs     40900000
73     74                                  Luisito Comunica     40600000
74     75                                       elrubiusOMG     40400000
75     76                                   Toys and Colors     40300000
76     77                                           shfa2 -     39700000
77     78                         LUCCAS NETO - LUCCAS TOON     39400000
78     79                                       CarryMinati     39200000
79     80                                      XXXTENTACION     39200000
80     81                   Super Simple Songs - Kids Songs     39200000
81     82                                         Mikecrack     39100000
82     83                                 WorkpointOfficial     39000000
83     84                                       GR6 EXPLODE     38900000
84     85                                        TEDx Talks     38600000
85     86                                              shfa     38400000
86     87                       Goldmines Gaane Sune Ansune     38300000
87     88                                     One Direction     38200000
88     89                                      TheEllenShow     38200000
89     90                                          Sony PAL     38200000
90     91                                      Daddy Yankee     38000000
91     92                                            Vlad v     37900000
92     93                                   Like Nastya ESP     37600000
93     94                                             one31     37500000
94     95                                 Jkk Entertainment     37200000
95     96                                          ABP NEWS     37000000
96     97                                    Maria Clara JP     37000000
97     98                                        Bruno Mars     36700000
98     99                                          Maroon 5     36600000
99    100                                   Ultra Bollywood     36600000
100   101                                      PowerKids TV     36500000
101   102                                           YouTube     36300000
102   103                                              News     36300000
103   104                                             Ozuna     36200000
104   105                                    MrBeast Gaming     36100000
105   106                                  La Granja de Zen     35700000
106   107                                    Saregama Music     35500000
107   108                                           IndiaTV     35500000
108   109                       T-Series Bollywood Classics     35400000
109   110                                      Total Gaming     35400000
110   111                                        Markiplier     35200000
111   112                                       Ryans World     35200000
112   113   Genevieves Playhouse - Learning Videos for Kids     34900000
113   114                              T-Series Apna Punjab     34600000
114   115                                     Techno Gamerz     34400000
115   116                                          Geet MP3     34300000
116   117                                          J Balvin     34100000
117   118                                     Jess No Limit     34000000
118   119                                      Jingle Toons     34000000
119   120                                        VEGETTA777     33800000
120   121                                Galinha Pintadinha     33800000
121   122                                      SSSniperWolf     33700000
122   123                                Desi Music Factory     33700000
123   124                                      Selena Gomez     33600000
124   125                                           Rajshri     33500000
125   126                                       Ch3Thailand     33500000
126   127                                  KHANDESHI MOVIES     33500000
127   128                                 NoCopyrightSounds     33400000
128   129                          CVS 3D Rhymes Kids Songs     33400000
129   130                                    Ricis Official     33300000
130   131                 BabyBus - Kids Songs and Cartoons     32800000
131   132                                    Eros Now Music     32700000
132   133                                           BETER B     32700000
133   134                                   DisneyMusicVEVO     32700000
134   135                                        The Weeknd     32600000
135   136                                           WowKidz     32200000
136   137                                           KAROL G     32100000
137   138                                           Mr Bean     32100000
138   139                                       rezendeevil     32100000
139   140                                          StarPlus     32000000
140   141                                            SMTOWN     31900000
141   142                                       GMA Network     31900000
142   143                                            GENIAL     31800000
143   144                                 MR. INDIAN HACKER     31700000
144   145                        Worldwide Records Bhojpuri     31700000
145   146                                              DONA     31700000
146   147                                             Dream     31700000
147   148                                  Lucas and Marcus     31600000
148   149                                  JustinBieberVEVO     31600000
149   150                                        Luis Fonsi     31400000
150   151                      Peppa Pig - Official Channel     31400000
151   152                                    YOLO AVENTURAS     31200000
152   153            The Tonight Show Starring Jimmy Fallon     31200000
153   154                                         TheDonato     31200000
154   155                                    ImagineDragons     30700000
155   156                                Diana and Roma ESP     30700000
156   157                                        Round2hell     30700000
157   158                                          Zee News     30500000
158   159                                           AboFlah     30500000
159   160                                                AH     30400000
160   161                                       Trap Nation     30400000
161   162                                                 0     30400000
162   163                                   Boram Tube Vlog     30300000
163   164                                             Adele     30200000
164   165                                       Talking Tom     30200000
165   166                                    toyoraljanahtv     30200000
166   167                                     Frost Diamond     30100000
167   168                                   Spinnin Records     30100000
168   169            Little Angel Nursery Rhymes Kids Songs     30100000
169   170                                     jacksepticeye     30100000
170   171                                      Shawn Mendes     30000000
171   172                           ashish chanchlani vines     29800000
172   173                                     Ultra Records     29600000
173   174                                Popular on YouTube     29300000
174   175                                            Maluma     29300000
175   176                                             Zhong     29200000
176   177                                         Enaldinho     29200000
177   178                                         AuronPlay     29200000
178   179                                      Shorts Break     29000000
179   180                                 infobells - Tamil     28900000
180   181                                Aditya Music India     28500000
181   182              The Late Late Show with James Corden     28400000
182   183                                     Aditya Movies     28400000
183   184                                    Masha y el Oso     28300000
184   185                                infobells - Telugu     28300000
185   186                                            HUM TV     28300000
186   187                                   Shemaroo Movies     28200000
187   188                                   Michael Jackson     28200000
188   189                                             Drake     28100000
189   190                                 Goldmines Dishoom     28000000
190   191                                Sandeep Maheshwari     27800000
191   192                        Bounce Patrol - Kids Songs     27800000
192   193                                       toycantando     27700000
193   194                                         MrBeast 2     27500000
194   195                                       Wiz Khalifa     27500000
195   196                                 JYP Entertainment     27400000
196   197                                    Kids Roma Show     27400000
197   198                                            DanTDM     27400000
198   199                                          Nick Jr.     27300000
199   200                                         Crazy XYZ     27300000
200   201                                      ToyPuddingTV     27100000
201   202                                  Dushyant kukreja     27100000
202   203                                     Gulshan Kalra     27100000
203   204                                      Brent Rivera     27000000
204   205                                  Renato Garcia YT     26900000
205   206                                      Beast Reacts     26700000
206   207                                         enchufetv     26700000
207   208                                           Netflix     26700000
208   209                             Raffy Tulfo in Action     26500000
209   210                                   WORLDSTARHIPHOP     26500000
210   211                               Goldmines Bollywood     26400000
211   212                                  Alan Chikin Chow     26400000
212   213                                         PANDA BOI     26400000
213   214                                       BB Ki Vines     26300000
214   215                                        D Billions     26200000
215   216                                            Junya.     26200000
216   217                                             Smosh     26100000
217   218                             1MILLION Dance Studio     26100000
218   219                                          NichLmao     26000000
219   220                                            Beyonc     26000000
220   221                                               Mar     26000000
221   222                                          Indosiar     25900000
222   223                                      VanossGaming     25800000
223   224                                      David Guetta     25700000
224   225                                     LosPolinesios     25700000
225   226                                       Nicki Minaj     25700000
226   227                                     Fede Vigevani     25600000
227   228                                   TaylorSwiftVEVO     25600000
228   229                                               ZHC     25500000
229   230                                       Post Malone     25500000
230   231                                Rans Entertainment     25400000
231   232                                          LankyBox     25400000
232   233                                          Coldplay     25300000
233   234                                       Las Ratitas     25200000
234   235                                           WB Kids     25200000
235   236                                           ABPLIVE     25200000
236   237                                       Chris Brown     25200000
237   238                                     The Lallantop     25200000
238   239                                       RihannaVEVO     25100000
239   240                                     WatchMojo.com     25100000
240   241                                   TRANS7 OFFICIAL     25000000
241   242                                          Anuel AA     25000000
242   243                                        Dan Rhodes     24800000
243   244                                              Yuya     24800000
244   245                               Americas Got Talent     24800000
245   246                                       mujjuu___14     24800000
246   247                                        EminemVEVO     24700000
247   248                                        Chloe Ting     24700000
248   249                                     KatyPerryVEVO     24600000
249   250                                        Mark Rober     24600000
250   251                                           1theK (     24500000
251   252                                    Like Nastya AE     24400000
252   253                                      Amit Bhadana     24300000
253   254                                        Pen Movies     24300000
254   255                                   MrBeast en Espa     24200000
255   256                                   shfa show India     24200000
256   257            Super JoJo - Nursery Rhymes Kids Songs     24100000
257   258                                        Alejo Igoa     24100000
258   259                                    Daniel LaBelle     24100000
259   260                                            netd m     24100000
260   261                                          DJ Snake     24100000
261   262                                Diana and Roma ARA     24100000
262   263                                               KSI     24100000
263   264                                      Spider Slack     24000000
264   265                                  Goldmines Movies     24000000
265   266                                           Preston     24000000
266   267                                     James Charles     23900000
267   268                                       Collins Key     23900000
268   269                                 Diana and Roma EN     23900000
269   270                               Venus Entertainment     23800000
270   271                                       Troom Troom     23800000
271   272                                  Enrique Iglesias     23800000

In [27]:
# Step 1. Remove dupliates

# 1.1. Check how many exact duplicate rows exist in df_cleaned
duplicate_count = df_cleaned.duplicated().sum()
print(f"Total duplicate rows found: {duplicate_count}")

# 1.2. Drop duplicates and keep the first occurrence
df_cleaned = df_cleaned.drop_duplicates()

# 1.3. Confirm that duplicates are removed
print(f"Duplicates remaining: {df_cleaned.duplicated().sum()}")
print(f"New dataset shape: {df_cleaned.shape}")

Total duplicate rows found: 0
Duplicates remaining: 0
New dataset shape: (995, 28)

In [28]:
# Step 2. Data Standardization

# Function to clean spaces, remove bad special characters, and fix text structure
def standardize_text(text):
    if text == "Unknown" or pd.isna(text):
        return "Unknown"
    
    text = str(text)
    
    # 1. Remove emojis and non-standard symbols but keep letters, numbers, and basic symbols
    cleaned = re.sub(r'[^a-zA-Z0-9\s\-_.,()&]', '', text)
    
    # 2. Fix extra spaces and structural spacing issues (e.g., "Hi   There" -> "Hi There")
    cleaned = " ".join(cleaned.split())
    
    return cleaned if cleaned.strip() != "" else "Unknown"

# Apply text standardization across all object/string columns dynamically
text_cols = df_cleaned.select_dtypes(include=['object']).columns

for col in text_cols:
    df_cleaned[col] = df_cleaned[col].apply(standardize_text)

print("--- Step 2.1: Text Columns Standardized Successfully ---")

--- Step 2.1: Text Columns Standardized Successfully ---

In [29]:
# Grouping all 28 columns into their precise, definitive datatypes
integer_columns = [
    'rank', 'subscribers', 'video views', 'uploads', 'video_views_rank', 
    'country_rank', 'channel_type_rank', 'video_views_for_the_last_30_days', 
    'subscribers_for_last_30_days', 'created_year'
]

float_columns = [
    'lowest_monthly_earnings', 'highest_monthly_earnings', 
    'lowest_yearly_earnings', 'highest_yearly_earnings',
    'Gross tertiary education enrollment (%)', 'Population', 
    'Unemployment rate', 'Urban_population', 'Latitude', 'Longitude'
]

string_category_columns = [
    'Youtuber', 'category', 'Title', 'Country', 'Abbreviation', 
    'channel_type', 'created_month'
]

# --- 1. Standardizing Integers ---
for col in integer_columns:
    if col in df_cleaned.columns:
        # Convert any logical errors/strings to numeric, fill blank spots with 0
        df_cleaned[col] = pd.to_numeric(df_cleaned[col], errors='coerce').fillna(0).astype('int64')

# --- 2. Standardizing Floats ---
for col in float_columns:
    if col in df_cleaned.columns:
        # Convert to float numbers, keep 0 for unknown structural values
        df_cleaned[col] = pd.to_numeric(df_cleaned[col], errors='coerce').fillna(0.0).astype('float64')

# --- 3. Standardizing Categories/Strings ---
for col in string_category_columns:
    if col in df_cleaned.columns:
        # Enforce uniform string format and strip trailing white spaces
        df_cleaned[col] = df_cleaned[col].astype(str).str.strip()

print("--- Step 2.2: Data Types Mapped & Converted Across All Columns ---")

--- Step 2.2: Data Types Mapped & Converted Across All Columns ---

In [30]:
# Print the datatype summary of the full dataset
print("--- FINAL DATATYPE VERIFICATION ---")
print(df_cleaned.info())

--- FINAL DATATYPE VERIFICATION ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 28 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   rank                                     995 non-null    int64
 1   Youtuber                                 995 non-null    object
 2   subscribers                              995 non-null    int64
 3   video views                              995 non-null    int64
 4   category                                 995 non-null    object
 5   Title                                    995 non-null    object
 6   uploads                                  995 non-null    int64
 7   Country                                  995 non-null    object
 8   Abbreviation                             995 non-null    object
 9   channel_type                             995 non-null    object
 10  video_views_rank                         995 non-null    int64
 11  country_rank                             995 non-null    int64
 12  channel_type_rank                        995 non-null    int64
 13  video_views_for_the_last_30_days         995 non-null    int64
 14  lowest_monthly_earnings                  995 non-null    float64
 15  highest_monthly_earnings                 995 non-null    float64
 16  lowest_yearly_earnings                   995 non-null    float64
 17  highest_yearly_earnings                  995 non-null    float64
 18  subscribers_for_last_30_days             995 non-null    int64
 19  created_year                             995 non-null    int64
 20  created_month                            995 non-null    object
 21  created_date                             995 non-null    object
 22  Gross tertiary education enrollment (%)  995 non-null    float64
 23  Population                               995 non-null    float64
 24  Unemployment rate                        995 non-null    float64
 25  Urban_population                         995 non-null    float64
 26  Latitude                                 995 non-null    float64
 27  Longitude                                995 non-null    float64
dtypes: float64(10), int64(10), object(8)
memory usage: 217.8+ KB
None

In [31]:
# 1. Clear any truncation limits for rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# 2. Display the dataframe again
df_cleaned

     rank                                          Youtuber  subscribers  \
0       1                                          T-Series    245000000
1       2                                    YouTube Movies    170000000
2       3                                           MrBeast    166000000
3       4                        Cocomelon - Nursery Rhymes    162000000
4       5                                         SET India    159000000
5       6                                             Music    119000000
6       7                                   Kids Diana Show    112000000
7       8                                         PewDiePie    111000000
8       9                                       Like Nastya    106000000
9      10                                     Vlad and Niki     98900000
10     11                                 Zee Music Company     96700000
11     12                                               WWE     96000000
12     13                                            Gaming     93600000
13     14                                         BLACKPINK     89800000
14     15                                         Goldmines     86900000
15     16                                          Sony SAB     83000000
16     17                                   5-Minute Crafts     80100000
17     18                                         BANGTANTV     75600000
18     19                                            Sports     75000000
19     20                                     Justin Bieber     71600000
20     21                                       HYBE LABELS     71300000
21     22                                            Zee TV     70500000
22     23          Pinkfong Baby Shark - Kids Songs Stories     68200000
23     24                                   Canal KondZilla     66500000
24     25               ChuChu TV Nursery Rhymes Kids Songs     65900000
25     26                              Shemaroo Filmi Gaane     65600000
26     27                                         Colors TV     64600000
27     28                             T-Series Bhakti Sagar     61000000
28     29                                      Dude Perfect     59500000
29     30                                        Movieclips     59500000
30     31                                     Tips Official     59300000
31     32                                 El Reino Infantil     58400000
32     33                                        Wave Music     58000000
33     34                                           Aaj Tak     57600000
34     35                                  Sony Music India     57200000
35     36                                       EminemMusic     56900000
36     37                                        Marshmello     56400000
37     38                                               YRF     54600000
38     39  LooLoo Kids - Nursery Rhymes and Childrens Songs     54000000
39     40                                        Ed Sheeran     53500000
40     41                                 Infobells - Hindi     53300000
41     42                                      Taylor Swift     52900000
42     43                                     Ariana Grande     52700000
43     44     BillionSurpriseToys - Nursery Rhymes Cartoons     52200000
44     45                                       JuegaGerman     48100000
45     46                                     Billie Eilish     47900000
46     47                                        Get Movies     47500000
47     48                                          Shemaroo     47400000
48     49                                           Badabun     46800000
49     50                                SonyMusicIndiaVEVO     46600000
50     51                                                A4     46300000
51     52                                         Bad Bunny     46100000
52     53                                        Fernanfloo     46100000
53     54                                         Voot Kids     45500000
54     55                                       Felipe Neto     45200000
55     56                                               Voc     44700000
56     57                                       HAR PAL GEO     44600000
57     58                                       BRIGHT SIDE     44500000
58     59                                        Katy Perry     44200000
59     60                                  whinderssonnunes     44200000
60     61                             ABS-CBN Entertainment     44200000
61     62                                       Alan Walker     43700000
62     63                                    HolaSoyGerman.     43600000
63     64                                           Shakira     43500000
64     65                                                 0     43200000
65     66                                    ARY Digital HD     43200000
66     67                                     Speed Records     42500000
67     68                                Masha and The Bear     42400000
68     69                                  Like Nastya Show     42400000
69     70                                           Rihanna     41900000
70     71                                      Ishtar Music     41400000
71     72                                   Kimberly Loaiza     41300000
72     73       Little Baby Bum - Nursery Rhymes Kids Songs     40900000
73     74                                  Luisito Comunica     40600000
74     75                                       elrubiusOMG     40400000
75     76                                   Toys and Colors     40300000
76     77                                           shfa2 -     39700000
77     78                         LUCCAS NETO - LUCCAS TOON     39400000
78     79                                       CarryMinati     39200000
79     80                                      XXXTENTACION     39200000
80     81                   Super Simple Songs - Kids Songs     39200000
81     82                                         Mikecrack     39100000
82     83                                 WorkpointOfficial     39000000
83     84                                       GR6 EXPLODE     38900000
84     85                                        TEDx Talks     38600000
85     86                                              shfa     38400000
86     87                       Goldmines Gaane Sune Ansune     38300000
87     88                                     One Direction     38200000
88     89                                      TheEllenShow     38200000
89     90                                          Sony PAL     38200000
90     91                                      Daddy Yankee     38000000
91     92                                            Vlad v     37900000
92     93                                   Like Nastya ESP     37600000
93     94                                             one31     37500000
94     95                                 Jkk Entertainment     37200000
95     96                                          ABP NEWS     37000000
96     97                                    Maria Clara JP     37000000
97     98                                        Bruno Mars     36700000
98     99                                          Maroon 5     36600000
99    100                                   Ultra Bollywood     36600000
100   101                                      PowerKids TV     36500000
101   102                                           YouTube     36300000
102   103                                              News     36300000
103   104                                             Ozuna     36200000
104   105                                    MrBeast Gaming     36100000
105   106                                  La Granja de Zen     35700000
106   107                                    Saregama Music     35500000
107   108                                           IndiaTV     35500000
108   109                       T-Series Bollywood Classics     35400000
109   110                                      Total Gaming     35400000
110   111                                        Markiplier     35200000
111   112                                       Ryans World     35200000
112   113   Genevieves Playhouse - Learning Videos for Kids     34900000
113   114                              T-Series Apna Punjab     34600000
114   115                                     Techno Gamerz     34400000
115   116                                          Geet MP3     34300000
116   117                                          J Balvin     34100000
117   118                                     Jess No Limit     34000000
118   119                                      Jingle Toons     34000000
119   120                                        VEGETTA777     33800000
120   121                                Galinha Pintadinha     33800000
121   122                                      SSSniperWolf     33700000
122   123                                Desi Music Factory     33700000
123   124                                      Selena Gomez     33600000
124   125                                           Rajshri     33500000
125   126                                       Ch3Thailand     33500000
126   127                                  KHANDESHI MOVIES     33500000
127   128                                 NoCopyrightSounds     33400000
128   129                          CVS 3D Rhymes Kids Songs     33400000
129   130                                    Ricis Official     33300000
130   131                 BabyBus - Kids Songs and Cartoons     32800000
131   132                                    Eros Now Music     32700000
132   133                                           BETER B     32700000
133   134                                   DisneyMusicVEVO     32700000
134   135                                        The Weeknd     32600000
135   136                                           WowKidz     32200000
136   137                                           KAROL G     32100000
137   138                                           Mr Bean     32100000
138   139                                       rezendeevil     32100000
139   140                                          StarPlus     32000000
140   141                                            SMTOWN     31900000
141   142                                       GMA Network     31900000
142   143                                            GENIAL     31800000
143   144                                 MR. INDIAN HACKER     31700000
144   145                        Worldwide Records Bhojpuri     31700000
145   146                                              DONA     31700000
146   147                                             Dream     31700000
147   148                                  Lucas and Marcus     31600000
148   149                                  JustinBieberVEVO     31600000
149   150                                        Luis Fonsi     31400000
150   151                      Peppa Pig - Official Channel     31400000
151   152                                    YOLO AVENTURAS     31200000
152   153            The Tonight Show Starring Jimmy Fallon     31200000
153   154                                         TheDonato     31200000
154   155                                    ImagineDragons     30700000
155   156                                Diana and Roma ESP     30700000
156   157                                        Round2hell     30700000
157   158                                          Zee News     30500000
158   159                                           AboFlah     30500000
159   160                                                AH     30400000
160   161                                       Trap Nation     30400000
161   162                                                 0     30400000
162   163                                   Boram Tube Vlog     30300000
163   164                                             Adele     30200000
164   165                                       Talking Tom     30200000
165   166                                    toyoraljanahtv     30200000
166   167                                     Frost Diamond     30100000
167   168                                   Spinnin Records     30100000
168   169            Little Angel Nursery Rhymes Kids Songs     30100000
169   170                                     jacksepticeye     30100000
170   171                                      Shawn Mendes     30000000
171   172                           ashish chanchlani vines     29800000
172   173                                     Ultra Records     29600000
173   174                                Popular on YouTube     29300000
174   175                                            Maluma     29300000
175   176                                             Zhong     29200000
176   177                                         Enaldinho     29200000
177   178                                         AuronPlay     29200000
178   179                                      Shorts Break     29000000
179   180                                 infobells - Tamil     28900000
180   181                                Aditya Music India     28500000
181   182              The Late Late Show with James Corden     28400000
182   183                                     Aditya Movies     28400000
183   184                                    Masha y el Oso     28300000
184   185                                infobells - Telugu     28300000
185   186                                            HUM TV     28300000
186   187                                   Shemaroo Movies     28200000
187   188                                   Michael Jackson     28200000
188   189                                             Drake     28100000
189   190                                 Goldmines Dishoom     28000000
190   191                                Sandeep Maheshwari     27800000
191   192                        Bounce Patrol - Kids Songs     27800000
192   193                                       toycantando     27700000
193   194                                         MrBeast 2     27500000
194   195                                       Wiz Khalifa     27500000
195   196                                 JYP Entertainment     27400000
196   197                                    Kids Roma Show     27400000
197   198                                            DanTDM     27400000
198   199                                          Nick Jr.     27300000
199   200                                         Crazy XYZ     27300000
200   201                                      ToyPuddingTV     27100000
201   202                                  Dushyant kukreja     27100000
202   203                                     Gulshan Kalra     27100000
203   204                                      Brent Rivera     27000000
204   205                                  Renato Garcia YT     26900000
205   206                                      Beast Reacts     26700000
206   207                                         enchufetv     26700000
207   208                                           Netflix     26700000
208   209                             Raffy Tulfo in Action     26500000
209   210                                   WORLDSTARHIPHOP     26500000
210   211                               Goldmines Bollywood     26400000
211   212                                  Alan Chikin Chow     26400000
212   213                                         PANDA BOI     26400000
213   214                                       BB Ki Vines     26300000
214   215                                        D Billions     26200000
215   216                                            Junya.     26200000
216   217                                             Smosh     26100000
217   218                             1MILLION Dance Studio     26100000
218   219                                          NichLmao     26000000
219   220                                            Beyonc     26000000
220   221                                               Mar     26000000
221   222                                          Indosiar     25900000
222   223                                      VanossGaming     25800000
223   224                                      David Guetta     25700000
224   225                                     LosPolinesios     25700000
225   226                                       Nicki Minaj     25700000
226   227                                     Fede Vigevani     25600000
227   228                                   TaylorSwiftVEVO     25600000
228   229                                               ZHC     25500000
229   230                                       Post Malone     25500000
230   231                                Rans Entertainment     25400000
231   232                                          LankyBox     25400000
232   233                                          Coldplay     25300000
233   234                                       Las Ratitas     25200000
234   235                                           WB Kids     25200000
235   236                                           ABPLIVE     25200000
236   237                                       Chris Brown     25200000
237   238                                     The Lallantop     25200000
238   239                                       RihannaVEVO     25100000
239   240                                     WatchMojo.com     25100000
240   241                                   TRANS7 OFFICIAL     25000000
241   242                                          Anuel AA     25000000
242   243                                        Dan Rhodes     24800000
243   244                                              Yuya     24800000
244   245                               Americas Got Talent     24800000
245   246                                       mujjuu___14     24800000
246   247                                        EminemVEVO     24700000
247   248                                        Chloe Ting     24700000
248   249                                     KatyPerryVEVO     24600000
249   250                                        Mark Rober     24600000
250   251                                           1theK (     24500000
251   252                                    Like Nastya AE     24400000
252   253                                      Amit Bhadana     24300000
253   254                                        Pen Movies     24300000
254   255                                   MrBeast en Espa     24200000
255   256                                   shfa show India     24200000
256   257            Super JoJo - Nursery Rhymes Kids Songs     24100000
257   258                                        Alejo Igoa     24100000
258   259                                    Daniel LaBelle     24100000
259   260                                            netd m     24100000
260   261                                          DJ Snake     24100000
261   262                                Diana and Roma ARA     24100000
262   263                                               KSI     24100000
263   264                                      Spider Slack     24000000
264   265                                  Goldmines Movies     24000000
265   266                                           Preston     24000000
266   267                                     James Charles     23900000
267   268                                       Collins Key     23900000
268   269                                 Diana and Roma EN     23900000
269   270                               Venus Entertainment     23800000
270   271                                       Troom Troom     23800000
271   272                                  Enrique Iglesias     23800000

In [32]:
# Step 4. REMOVE UNNECESSARY COLUMNS (KEEP 7, DELETE 21)
# We only need 7 columns out of 28 because we will analyze my question and get inghts from these 7 columns and the remaining 21 column is unnecessary,
# if let suppose we will get more question to analyze so we have our raw dataset is on backup for this work we just need these columns.
# Defining the exact 7 columns needed for our project analysis
columns_to_keep = [
    'Youtuber', 
    'subscribers', 
    'video views', 
    'category', 
    'Country', 
    'highest_monthly_earnings', 
    'subscribers_for_last_30_days'
]

# Filtering df_cleaned to keep ONLY these 7 columns. 
# The other 21 columns (like rank, uploads, population, latitude, etc.) are deleted here.
df_cleaned = df_cleaned[columns_to_keep].copy()

In [33]:
# 1. Clear any truncation limits for rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# 2. Display the dataframe again
df_cleaned

,Youtuber,subscribers,video views,category,Country,highest_monthly_earnings,subscribers_for_last_30_days
0,T-Series,245000000,228000000000,Music,India,9000000,2000000
1,YouTube Movies,170000000,0,Film Animation,United States,0,0
2,MrBeast,166000000,28368841870,Entertainment,United States,5400000,8000000
3,Cocomelon - Nursery Rhymes,162000000,164000000000,Education,United States,7900000,1000000
4,SET India,159000000,148000000000,Shows,India,7300000,1000000
5,Music,119000000,0,Unknown,Unknown,0,0
6,Kids Diana Show,112000000,93247040539,People Blogs,United States,2900000,0
7,PewDiePie,111000000,29058044447,Gaming,Japan,156700,0
8,Like Nastya,106000000,90479060027,People Blogs,Russia,195800,100000
9,Vlad and Niki,98900000,77180169894,Entertainment,United States,2300000,600000
10,Zee Music Company,96700000,57856289381,Music,India,3200000,1100000
11,WWE,96000000,77428473662,Sports,United States,2900000,600000
12,Gaming,93600000,0,Unknown,Unknown,0,0
13,BLACKPINK,89800000,32144597566,People Blogs,South Korea,2000000,700000
14,Goldmines,86900000,24118230580,Film Animation,Unknown,0,0
15,Sony SAB,83000000,101000000000,Shows,India,6600000,1100000
16,5-Minute Crafts,80100000,26236790209,Howto Style,United Kingdom,0,0
17,BANGTANTV,75600000,20826993957,Music,South Korea,673200,400000
18,Sports,75000000,0,Unknown,United States,0,0
19,Justin Bieber,71600000,30608119724,Music,Canada,705300,100000
20,HYBE LABELS,71300000,28634566938,Music,South Korea,2400000,900000
21,Zee TV,70500000,73139054467,Entertainment,India,6800000,900000
22,Pinkfong Baby Shark - Kids Songs Stories,68200000,38843229963,Education,United States,1900000,600000
23,Canal KondZilla,66500000,36775585925,Music,Brazil,0,0
24,ChuChu TV Nursery Rhymes Kids Songs,65900000,45757850229,Education,India,1700000,500000
25,Shemaroo Filmi Gaane,65600000,28648024439,Music,India,1000000,400000
26,Colors TV,64600000,61510906457,Shows,India,4800000,1100000
27,T-Series Bhakti Sagar,61000000,29533230328,Music,India,0,0
28,Dude Perfect,59500000,16241549158,Sports,United States,564800,100000
29,Movieclips,59500000,59316472754,Film Animation,United States,458700,100000
30,Tips Official,59300000,33431802698,Music,India,1700000,600000
31,El Reino Infantil,58400000,57271630846,Music,Argentina,2400000,600000
32,Wave Music,58000000,40602020243,Music,India,928100,500000
33,Aaj Tak,57600000,25307753534,News Politics,India,1800000,500000
34,Sony Music India,57200000,28837144516,Music,India,1000000,300000
35,EminemMusic,56900000,27073872856,Music,United States,1000000,300000
36,Marshmello,56400000,14696003229,Entertainment,United States,448400,100000
37,YRF,54600000,35302243691,Film Animation,India,2000000,500000
38,LooLoo Kids - Nursery Rhymes and Childrens Songs,54000000,32312431239,Music,Unknown,1,0
39,Ed Sheeran,53500000,30367676736,Music,United Kingdom,810900,100000
40,Infobells - Hindi,53300000,30516172739,Education,India,3300000,1600000
41,Taylor Swift,52900000,29884657286,Music,United States,2100000,800000
42,Ariana Grande,52700000,24004842608,Music,United States,640900,100000
43,BillionSurpriseToys - Nursery Rhymes Cartoons,52200000,9877365274,Education,United States,1100000,600000
44,JuegaGerman,48100000,14631710289,Gaming,Chile,265600,200000
45,Billie Eilish,47900000,13626331061,Music,United States,587400,200000
46,Get Movies,47500000,30788679536,Entertainment,Russia,1200000,700000
47,Shemaroo,47400000,22519705183,Entertainment,India,931000,500000
48,Badabun,46800000,19398045702,Entertainment,Unknown,2,75
49,SonyMusicIndiaVEVO,46600000,27286058807,Music,United States,1300000,400000
50,A4,46300000,22936630813,Gaming,Cuba,0,10
51,Bad Bunny,46100000,30686342319,Music,Unknown,0,0
52,Fernanfloo,46100000,10323391593,Gaming,El Salvador,135400,200000
53,Voot Kids,45500000,21388725229,Entertainment,India,936000,400000
54,Felipe Neto,45200000,16602198273,Entertainment,Brazil,521400,200000
55,Voc,44700000,7828610828,Entertainment,Brazil,192100,100000
56,HAR PAL GEO,44600000,41139050371,Entertainment,Pakistan,5300000,1300000
57,BRIGHT SIDE,44500000,10708531817,Howto Style,Unknown,0,1
58,Katy Perry,44200000,25458952022,Music,United States,537000,100000
59,whinderssonnunes,44200000,4274709210,Comedy,Brazil,106700,0
60,ABS-CBN Entertainment,44200000,50292540392,People Blogs,Philippines,706500,300000
61,Alan Walker,43700000,12884264778,Music,Thailand,0,0
62,HolaSoyGerman.,43600000,4831311245,Entertainment,Unknown,0,0
63,Shakira,43500000,27568757295,People Blogs,Colombia,1400000,500000
64,0,43200000,36458726976,Film Animation,Russia,1200000,300000
65,ARY Digital HD,43200000,37939780685,Entertainment,Pakistan,4600000,900000
66,Speed Records,42500000,26820902622,Music,India,639000,100000
67,Masha and The Bear,42400000,24519022988,Shows,United States,2700000,1000000
68,Like Nastya Show,42400000,19547696190,Entertainment,United States,212800,0
69,Rihanna,41900000,22477745835,Entertainment,Barbados,731700,100000
70,Ishtar Music,41400000,17608931161,Trailers,India,723800,400000
71,Kimberly Loaiza,41300000,5603111948,People Blogs,Mexico,547000,400000
72,Little Baby Bum - Nursery Rhymes Kids Songs,40900000,39450824833,Education,United States,395100,100000
73,Luisito Comunica,40600000,8670473639,Comedy,Mexico,0,0
74,elrubiusOMG,40400000,7410536668,Gaming,Unknown,23100,0
75,Toys and Colors,40300000,47005053156,Entertainment,Unknown,0,0
76,shfa2 -,39700000,23884824160,People Blogs,United Arab Emirates,990900,300000
77,LUCCAS NETO - LUCCAS TOON,39400000,22302547082,People Blogs,Unknown,0,0
78,CarryMinati,39200000,3294013141,Comedy,India,314800,700000
79,XXXTENTACION,39200000,10507474316,Music,United States,233400,100000
80,Super Simple Songs - Kids Songs,39200000,44900897958,Education,Canada,2200000,400000
81,Mikecrack,39100000,16118181673,Gaming,Spain,1100000,800000
82,WorkpointOfficial,39000000,36131228583,Entertainment,Thailand,521800,200000
83,GR6 EXPLODE,38900000,25154232306,Music,Brazil,6500000,100000
84,TEDx Talks,38600000,7339333120,Nonprofits Activism,United States,182600,100000
85,shfa,38400000,21528116909,People Blogs,Saudi Arabia,6400,2000
86,Goldmines Gaane Sune Ansune,38300000,16718192386,Music,India,3300000,400000
87,One Direction,38200000,13598903820,Music,United States,25,100
88,TheEllenShow,38200000,22756581750,Entertainment,United States,87200,0
89,Sony PAL,38200000,28519339489,Shows,India,1700000,500000
90,Daddy Yankee,38000000,22731415608,Music,United States,822400,100000
91,Vlad v,37900000,23510152352,Unknown,United States,976400,200000
92,Like Nastya ESP,37600000,18208196857,Entertainment,United States,1300000,700000
93,one31,37500000,27262462114,Entertainment,Thailand,563000,300000
94,Jkk Entertainment,37200000,16402066717,Comedy,India,199400,100000
95,ABP NEWS,37000000,13102611515,People Blogs,India,1100000,400000
96,Maria Clara JP,37000000,24188861917,People Blogs,Brazil,1000000,300000
97,Bruno Mars,36700000,19378155425,Music,United States,701000,200000
98,Maroon 5,36600000,22553923546,Music,United States,611300,0
99,Ultra Bollywood,36600000,15653786446,Trailers,India,0,200000
100,PowerKids TV,36500000,18961241905,Film Animation,Unknown,1300000,600000
101,YouTube,36300000,3010784935,News Politics,United States,84400,300000
102,News,36300000,0,Unknown,Unknown,0,0
103,Ozuna,36200000,23355801606,Music,Unknown,677000,100000
104,MrBeast Gaming,36100000,6331332547,Gaming,Unknown,0,1
105,La Granja de Zen,35700000,27118354077,Music,Argentina,1200000,400000
106,Saregama Music,35500000,15657673422,Entertainment,India,2100000,900000
107,IndiaTV,35500000,16105023749,News Politics,India,1200000,600000
108,T-Series Bollywood Classics,35400000,22637783517,Music,India,1300000,500000
109,Total Gaming,35400000,5556364230,Gaming,Unknown,0,2
110,Markiplier,35200000,20297931219,Gaming,United States,509300,100000
111,Ryans World,35200000,55299840198,Entertainment,United States,954500,200000
112,Genevieves Playhouse - Learning Videos for Kids,34900000,25607397308,Education,United States,1300000,300000
113,T-Series Apna Punjab,34600000,21306315429,Music,Unknown,0,0
114,Techno Gamerz,34400000,9690499664,Gaming,Unknown,0,3
115,Geet MP3,34300000,12746535822,Music,India,405400,100000
116,J Balvin,34100000,23005313609,Music,Colombia,514800,100000
117,Jess No Limit,34000000,3963007415,Entertainment,Indonesia,2200000,5500000
118,Jingle Toons,34000000,11351015824,Film Animation,India,719600,600000
119,VEGETTA777,33800000,15432929204,Gaming,Spain,156400,0
120,Galinha Pintadinha,33800000,27274550757,Film Animation,Brazil,1600000,200000
121,SSSniperWolf,33700000,23492684419,Gaming,United States,843800,200000
122,Desi Music Factory,33700000,10189027455,Music,Unknown,0,0
123,Selena Gomez,33600000,13013567335,Film Animation,United States,463200,200000
124,Rajshri,33500000,14864294792,Music,India,1100000,500000
125,Ch3Thailand,33500000,29611914495,Entertainment,Thailand,0,100000
126,KHANDESHI MOVIES,33500000,11405809704,Comedy,India,98900,100000
127,NoCopyrightSounds,33400000,10530729078,Music,United Kingdom,222600,0
128,CVS 3D Rhymes Kids Songs,33400000,20269857567,Education,India,544300,200000
129,Ricis Official,33300000,5994136760,People Blogs,Indonesia,628400,1900000
130,BabyBus - Kids Songs and Cartoons,32800000,26355088167,Education,United States,510000,200000
131,Eros Now Music,32700000,17853798780,Entertainment,India,81100,40000
132,BETER B,32700000,19180039918,Unknown,Turkey,5900000,2100000
133,DisneyMusicVEVO,32700000,28516250629,Music,United States,1300000,300000
134,The Weeknd,32600000,23379969006,Music,Canada,1500000,200000
135,WowKidz,32200000,16613441479,Film Animation,Unknown,0,0
136,KAROL G,32100000,18699145555,Music,Colombia,1900000,300000
137,Mr Bean,32100000,10602236110,Shows,United Kingdom,226100,100000
138,rezendeevil,32100000,13061739758,Gaming,Brazil,178000,0
139,StarPlus,32000000,26800674545,Entertainment,India,6700000,1200000
140,SMTOWN,31900000,27330239663,Music,Unknown,933600,100000
141,GMA Network,31900000,19428308461,Entertainment,Philippines,3200000,500000
142,GENIAL,31800000,6762424690,Howto Style,Mexico,125800,0
143,MR. INDIAN HACKER,31700000,5711208484,Science Technology,India,436500,500000
144,Worldwide Records Bhojpuri,31700000,16476978876,Music,India,450600,200000
145,DONA,31700000,21031745531,Entertainment,United States,613100,200000
146,Dream,31700000,2930015381,Gaming,United States,108100,200000
147,Lucas and Marcus,31600000,11615848291,Entertainment,United States,1200000,400000
148,JustinBieberVEVO,31600000,26583873105,Music,United States,420500,0
149,Luis Fonsi,31400000,15176762479,Entertainment,Unknown,0,0
150,Peppa Pig - Official Channel,31400000,22919271731,Film Animation,United Kingdom,979700,300000
151,YOLO AVENTURAS,31200000,9673649438,People Blogs,Venezuela,14,100
152,The Tonight Show Starring Jimmy Fallon,31200000,17111726160,Comedy,United States,0,100000
153,TheDonato,31200000,6187804950,Entertainment,Argentina,762700,1900000
154,ImagineDragons,30700000,16793072362,Music,United States,755300,100000
155,Diana and Roma ESP,30700000,12355992466,Unknown,United States,412000,200000
156,Round2hell,30700000,3145161634,Comedy,India,127300,300000
157,Zee News,30500000,16709857823,News Politics,India,1800000,600000
158,AboFlah,30500000,4521573939,Gaming,Kuwait,631600,1300000
159,AH,30400000,4332274962,Entertainment,Indonesia,85800,0
160,Trap Nation,30400000,14037426379,Music,United States,183300,0
161,0,30400000,17999961915,Unknown,United States,491700,300000
162,Boram Tube Vlog,30300000,13546549817,Entertainment,United States,90900,0
163,Adele,30200000,14199108016,Music,United Kingdom,548400,100000
164,Talking Tom,30200000,15199330166,Comedy,United States,0,0
165,toyoraljanahtv,30200000,27684955537,Entertainment,Jordan,465700,100000
166,Frost Diamond,30100000,7277493940,Gaming,Unknown,0,6
167,Spinnin Records,30100000,19607009165,Music,Netherlands,400200,100000
168,Little Angel Nursery Rhymes Kids Songs,30100000,22593193994,Education,United States,430100,0
169,jacksepticeye,30100000,16246625836,Gaming,Unknown,161700,100000
170,Shawn Mendes,30000000,12831200855,Music,Canada,355000,0
171,ashish chanchlani vines,29800000,4457913639,Comedy,India,104700,100000
172,Ultra Records,29600000,17208027242,Music,United States,327500,0
173,Popular on YouTube,29300000,0,Unknown,Unknown,0,0
174,Maluma,29300000,21226945136,Music,Argentina,0,0
175,Zhong,29200000,14727238483,Entertainment,United States,0,1000000
176,Enaldinho,29200000,11627437847,Comedy,Brazil,1200000,1000000
177,AuronPlay,29200000,4079141673,Comedy,Spain,48600,0
178,Shorts Break,29000000,19466238065,Comedy,Unknown,243,151
179,infobells - Tamil,28900000,17930570614,Education,India,439300,200000
180,Aditya Music India,28500000,25857994495,Music,Unknown,0,0
181,The Late Late Show with James Corden,28400000,9956764048,Entertainment,United States,105700,0
182,Aditya Movies,28400000,10062770060,Movies,India,909400,500000
183,Masha y el Oso,28300000,13577142726,Film Animation,Unknown,0,0
184,infobells - Telugu,28300000,14814192034,Education,India,1200000,800000
185,HUM TV,28300000,23844936965,Entertainment,Pakistan,2700000,700000
186,Shemaroo Movies,28200000,7600740993,Entertainment,India,739900,500000
187,Michael Jackson,28200000,14412474625,Music,United States,634400,200000
188,Drake,28100000,15318895118,Music,Unknown,0,1
189,Goldmines Dishoom,28000000,8603468420,Film Animation,Unknown,516800,400000
190,Sandeep Maheshwari,27800000,2303069221,People Blogs,Singapore,0,1
191,Bounce Patrol - Kids Songs,27800000,21037851468,Music,Australia,509800,0
192,toycantando,27700000,15777682516,Music,Colombia,695300,200000
193,MrBeast 2,27500000,4552581106,People Blogs,United States,0,0
194,Wiz Khalifa,27500000,13379395501,Music,United States,361800,100000
195,JYP Entertainment,27400000,19883150017,Music,South Korea,1200000,200000
196,Kids Roma Show,27400000,10336420490,People Blogs,United States,703400,400000
197,DanTDM,27400000,19417887510,Gaming,United Kingdom,314700,500000
198,Nick Jr.,27300000,22440611155,Film Animation,United States,170200,200000
199,Crazy XYZ,27300000,7705492350,Entertainment,India,408900,100000
200,ToyPuddingTV,27100000,15916882228,Entertainment,Unknown,0,0
201,Dushyant kukreja,27100000,17318452893,Entertainment,India,1700000,700000
202,Gulshan Kalra,27100000,12732444881,Howto Style,Unknown,2000000,1300000
203,Brent Rivera,27000000,6570935979,Comedy,United States,577800,300000
204,Renato Garcia YT,26900000,7938616641,Entertainment,Brazil,331600,200000
205,Beast Reacts,26700000,4388047013,People Blogs,United States,1100000,1200000
206,enchufetv,26700000,10317306313,Comedy,Colombia,97500,0
207,Netflix,26700000,7173668905,Entertainment,United States,472900,200000
208,Raffy Tulfo in Action,26500000,15065753455,News Politics,Philippines,652500,300000
209,WORLDSTARHIPHOP,26500000,20358117330,Music,United States,356400,0
210,Goldmines Bollywood,26400000,8595760553,Film Animation,India,398700,400000
211,Alan Chikin Chow,26400000,27006526665,Comedy,United States,4200000,1300000
212,PANDA BOI,26400000,17211600007,Entertainment,Italy,4900000,2000000
213,BB Ki Vines,26300000,4749833967,Entertainment,India,69100,0
214,D Billions,26200000,31977463002,Unknown,United States,1900000,200000
215,Junya.,26200000,16097531087,Entertainment,Japan,2900000,1100000
216,Smosh,26100000,10435474336,Comedy,United States,272600,400000
217,1MILLION Dance Studio,26100000,7886440199,Entertainment,Saudi Arabia,0,0
218,NichLmao,26000000,14101010609,People Blogs,Unknown,2400000,1100000
219,Beyonc,26000000,17308961985,Music,United States,221800,0
220,Mar,26000000,18597534412,Music,Unknown,0,3
221,Indosiar,25900000,11372071889,Music,Indonesia,920700,600000
222,VanossGaming,25800000,15541421838,Gaming,Canada,219800,0
223,David Guetta,25700000,17793809548,Music,United States,656900,100000
224,LosPolinesios,25700000,7466926260,People Blogs,Mexico,122000,0
225,Nicki Minaj,25700000,10242981063,Music,United States,414500,100000
226,Fede Vigevani,25600000,7962725960,Howto Style,Unknown,0,2
227,TaylorSwiftVEVO,25600000,25592378292,Music,United States,1300000,100000
228,ZHC,25500000,2726917087,Film Animation,Unknown,0,4
229,Post Malone,25500000,14401218086,Music,United States,782000,100000
230,Rans Entertainment,25400000,6430853035,People Blogs,Indonesia,233900,100000
231,LankyBox,25400000,34300482066,Comedy,United States,3300000,600000
232,Coldplay,25300000,17331663193,Music,United Kingdom,795500,100000
233,Las Ratitas,25200000,9602246828,People Blogs,Unknown,0,0
234,WB Kids,25200000,11081602368,People Blogs,United States,561300,300000
235,ABPLIVE,25200000,7968363381,People Blogs,Unknown,0,0
236,Chris Brown,25200000,15520569496,Music,Unknown,0,0
237,The Lallantop,25200000,10409352249,News Politics,India,1100000,300000
238,RihannaVEVO,25100000,19458807708,Music,United States,377000,0
239,WatchMojo.com,25100000,16357064198,Music,Canada,196000,0
240,TRANS7 OFFICIAL,25000000,14169516119,Entertainment,Indonesia,492800,100000
241,Anuel AA,25000000,14827085149,Music,Colombia,1100000,300000
242,Dan Rhodes,24800000,17387583720,Entertainment,United Kingdom,1300000,500000
243,Yuya,24800000,2588501115,Howto Style,Mexico,1300,0
244,Americas Got Talent,24800000,3699352704,Entertainment,United States,537600,400000
245,mujjuu___14,24800000,14655527943,People Blogs,Unknown,1600000,900000
246,EminemVEVO,24700000,20531704527,Music,United States,557800,100000
247,Chloe Ting,24700000,2994726412,Howto Style,Australia,93100,0
248,KatyPerryVEVO,24600000,23755792542,Music,United States,355800,100000
249,Mark Rober,24600000,3647987299,Science Technology,United States,354500,200000
250,1theK (,24500000,23962070944,Music,South Korea,422300,0
251,Like Nastya AE,24400000,12385924995,Entertainment,United States,679500,400000
252,Amit Bhadana,24300000,2380248899,Entertainment,Unknown,0,0
253,Pen Movies,24300000,6608773195,Film Animation,India,379400,300000
254,MrBeast en Espa,24200000,2700914170,Entertainment,Mexico,134400,100000
255,shfa show India,24200000,15724160183,Unknown,United Arab Emirates,604800,200000
256,Super JoJo - Nursery Rhymes Kids Songs,24100000,329774870,Unknown,United States,1300000,100000
257,Alejo Igoa,24100000,10999000479,Comedy,Argentina,1600000,600000
258,Daniel LaBelle,24100000,12916159065,Comedy,Unknown,1600000,700000
259,netd m,24100000,56106087508,Music,Turkey,1700000,200000
260,DJ Snake,24100000,8425505919,Music,United States,253200,0
261,Diana and Roma ARA,24100000,11041261296,Unknown,United States,267500,200000
262,KSI,24100000,6002166932,Entertainment,United Kingdom,21800,0
263,Spider Slack,24000000,13943030228,Comedy,Brazil,3000000,1100000
264,Goldmines Movies,24000000,5652938599,Film Animation,Unknown,0,0
265,Preston,24000000,8279004442,Gaming,United States,606800,200000
266,James Charles,23900000,4067878931,Entertainment,United States,232500,100000
267,Collins Key,23900000,6582932625,Entertainment,United States,43400,0
268,Diana and Roma EN,23900000,7213499085,People Blogs,United States,711100,300000
269,Venus Entertainment,23800000,5663125358,Entertainment,Unknown,127,0
270,Troom Troom,23800000,10414479943,Howto Style,United States,392200,100000
271,Enrique Iglesias,23800000,17688774915,Music,United States,491700,100000
272,Ninja,23700000,2543809954,Gaming,United States,33500,0
273,FaZe Rug,23700000,7451792132,Gaming,Canada,0,1
274,Mister Max,23700000,15510153803,People Blogs,United Kingdom,131300,0
275,That Little Puff,23700000,20289689389,Pets Animals,United States,3000000,1100000
276,NickyJamTV,23600000,15901824841,Music,Unknown,311700,100000
277,Juan De Dios Pantoja,23600000,2135644776,Entertainment,Mexico,187400,200000
278,Logan Paul,23600000,5994002464,Entertainment,United States,43200,0
279,Maya and Mary,23600000,6766461070,Entertainment,United States,178200,400000
280,Peppa Pig Espa,23600000,7920637200,Film Animation,United Kingdom,214400,100000
281,Jelly,23500000,14777034543,Gaming,United Kingdom,166700,0
282,Miss Katy,23500000,14696994366,People Blogs,United Kingdom,238500,0
283,Tilak,23400000,9465863821,Film Animation,India,1500000,900000

In [36]:
# Save the dataset as a real Excel file instead of CSV
excel_output_path = r"F:\Data Analytics Real time Project portfolio\Global Youtube Statistics\Cleaned_Dataset_Global_YouTube_Statistics.xlsx"

# Using openpyxl engine to write a clean Excel sheet
df_cleaned.to_excel(excel_output_path, index=False)

print(" File Successfully Download ")

 File Successfully Download